- Dockerfile
- nextflow.config
This PR updates the Dockerfile by adding both guppy and conda dependencies in one container.
> Updates the docker container (both guppy+conda together)

- conf/google.config
- main.nf
- nextflow.config
This PR enables use of --config and also enables run with gpu machines.
> Enable cloud execution with gpus

- conf/google.config
- conf/standard.config
- nextflow.config
We finished the cloud container with Lifebit team
> We finished the cloud container test with Lifebit team

- Dockerfile
- conf/google.config
This PR add `git` as an extra dependency.
To check if the dependency is properly installed use the following commands:
To use/enter the container:
```bash
docker run --rm  -it quay.io/lifebitai/nanome
```
Inside the container, to check if git is installed:
```bash
git --version
```
You should see the following git version:
```console
git version 2.7.4
```
> Add git in Dockerfile; Rename to quay.io/lifebitai/nanome

- README.md
> add system requirement to readme

- .gitignore
> clean source codes

- conf/benchmarking.config
- conf/ecoli_demo.config
- conf/hpc.config
- conf/test.config
- docs/Usage.md
- main.nf
- main.sbatch
- nextflow.config
- src/nanocompare/read_level_eval.py
- utils/clean_old_basecall_in_fast5.py
Make robust with both human and e. coli
> Make robust with both human and e. coli

- Dockerfile
- conf/google.config
- main.nf
- src/nanocompare/benchmarkingDataConstruct.py
- src/nanocompare/computeRawReadsCoverage.py
- src/nanocompare/eval_common.py
- src/nanocompare/global_config.py
- src/nanocompare/global_settings.py
- src/nanocompare/read_level_eval.py
- src/nanocompare/read_level_eval_submit.py
- src/nanocompare/site_level_eval.py
- src/nanocompare/site_level_eval_submit.py
- src/nanocompare/test_script.py
- src/nanocompare/tss_eval.py
- src/nanocompare/tss_eval_submit.py
- src/plot_figure.py
- utils/FilesSeparatorNew.py
- utils/clean_old_basecall_in_fast5.py
- utils/hm_cluster_predict.py
- utils/nanopore_nanopolish_preindexing_checkDups.py
- utils/sum_chr_mod.py
- utils/tombo_extract_per_read_stats.py
:warning: Do not merge yet - to be discussed.
This PR is addressing the issue found `libcuda.so.1` not found that affects `guppy_basecaller` command.
> Adds GPU drivers (CUDA) in the container

- Dockerfile
This PR addresses the issue of the interactive command prompt in the cuda install step, see below.
> Fixes interactive mode issue for languages

- conf/tool_options_on_gpu.config
- docs/Usage.md
- inputs/NA12878CHR20_2.filelist.txt
- main.nf
- main.sbatch
tagname for DeepSignal and Tombo
> tagname for DeepSignal and Tombo

- src/nanocompare/utils/datasets_readlength_portion.py
> pull test2

- src/nanocompare/eval_common.py
- src/nanocompare/read_level_eval.py
- src/nanocompare/site_level_eval.py
- src/paper_read_level_performance.sbatch
- src/paper_read_level_performance_submit.sh
- src/paper_site_level_correlation.sbatch
- src/paper_site_level_correlation_submit.sh
> add comments

- src/nanocompare/computeRawReadsCoverage.py
- src/nanocompare/computeRawReadsCoverage.sh
- src/nanocompare/eval_common.py
- src/nanocompare/global_settings.py
- src/nanocompare/read_level_eval.py
- src/nanocompare/site_level_eval.py
- src/nanocompare/tss_eval.py
- src/paper_meteore_format_of_tools.sbatch
- src/paper_read_level_performance.sbatch
- src/paper_read_level_performance_submit.sh
- src/paper_tss_data_generation.sbatch
- src/paper_tss_data_generation_submit.sh
> pull request

- src/nanocompare/eval_common.py
- src/nanocompare/global_settings.py
- src/nanocompare/read_level_eval.py
- src/nanocompare/sanity_check_deepmod.py
- src/nanocompare/site_level_eval.py
- src/paper_read_level_performance.sbatch
- src/paper_site_level_correlation.sbatch
- src/paper_site_level_correlation_submit.sh
- src/paper_tss_data_generation.sbatch
- src/plot_figure.sh
> add guppy gcf52 support

- README.md
- do_build.sh
- docs/Usage.md
- main.nf
- main.sbatch
- nextflow.config
- run_on_google_cloud.sbatch
- src/nanocompare/tss_eval.py
> add fast5mod to readme

- docs/Usage.md
- docs/outputs.tree.txt
- docs/work.tree.txt
> edit usage

- conf/gcp.config
- conf/google.config
- docs/Usage.md
- main.nf
- nextflow.config
> add comments to nextflow

- demo_hpc_winter.sh
- inputs/test.demo.filelist.txt
- main.nf
> add main.nf doc

- docs/Usage.md
> demo doc ok

- benchmark_hpc_winter.sh
- conf/benchmarking.config
- demo_google_cloud.sh
- demo_hpc_winter.sh
- docs/Usage.md
- ecoli_hpc_winter.sh
- main.nf
- nextflow.config
- src/nanocompare/tss_eval.py
> add ecoli comments and docs

- demo_hpc_winter.sh
- main.nf
change file to path for nextflow
> change file to path for nextflow

- demo_hpc_winter.sh
- docs/Usage.md
- main.nf
- nextflow.config
- utils/gen_readme.py
- utils/readme.txt.template
support docker, and singularity
> support docker, and singularity

- main.nf
> add readme to outputs

- demo_hpc_winter.sh
- docs/Usage.md
- main.nf
- nextflow.config
- src/nanocompare/tss_eval.py
> command help docs

- README.md
- demo_hpc_winter.sh
- docs/Usage.md
- main.nf
- nextflow.config
> add command help doc

- demo_hpc_winter.sh
- inputs/test2.demo.filelist.txt
- main.nf
- src/nanocompare/computeRawReadsCoverage.py
- src/nanocompare/eval_common.py
- src/nanocompare/read_level_eval.py
- src/nanocompare/report/gen_html_report.py
- src/nanocompare/site_level_eval.py
- src/nanocompare/tss_eval.py
- src/nanocompare/utils/meth_stats_tool.py
- src/nanocompare/utils/saniti-ecoli/sanity_check_deepmod.py
- src/nanocompare/utils/saniti-ecoli/sanity_check_deepmod.sbatch
- src/nanocompare/utils/saniti-ecoli/sanity_check_deepmod_paper.sbatch
- src/nanocompare/utils/saniti-ecoli/sanity_check_deepmod_paper_all_chrs.sh
- src/plot_figure.py
- utils/sum_chr_mod.py
> add copyright

- .github/workflows/ci.yml
- .gitignore
- README.md
- conf/ci.config
- conf/ecoli_demo.config
- demo_hpc_winter.sh
- ecoli_hpc_winter.sh
- main.nf
- nextflow.config
- utils/combination_model_prediction.py
> CI test for nanome

- src/nanocompare/report/gen_html_report.py
- src/nanocompare/report/index.html
> add coverage to html report

- .gitignore
- README.md
- conf/ci.config
- conf/ecoli_demo.config
- conf/gc_params.config
- conf/jax_hpc.config
- conf/lifebit_cloudos.config
- conf/local.config
- conf/standard.config
- conf/zenodo_params.config
- docs/Usage.md
- main.nf
- nextflow.config
Add Lifebit platform configurations
> Add Lifebit platform configurations

- .github/workflows/ci.yml
- conf/ci.config
- conf/ci_human.config
- main.nf
- nextflow.config
- utils/hm_cluster_predict.py
add CI test case for human data
> add CI test case for human data

- conf/ci_human.config
- conf/lifebit.config
- demo_google_cloud.sh
- demo_hpc_winter.sh
- docs/Usage.md
- main.nf
- nextflow.config
- src/deepmod/reproduce_deepmod_na12878.py
- src/nanocompare/computeRawReadsCoverage.py
- src/nanocompare/eval_common.py
- src/nanocompare/read_level_eval.py
- src/nanocompare/report/gen_html_report.py
- src/nanocompare/report/index.html
- src/nanocompare/site_level_eval.py
- src/nanocompare/tss_eval.py
- src/nanocompare/utils/meth_stats_tool.py
- src/plot_figure.py
- utils/FilesSeparator.py
- utils/readme.txt.template
Enhance pipeline running on Lifebit CloudOS
> Lifebit running enhance

- .gitignore
- Dockerfile
- README.md
- conf/lifebit.config
- demo_google_cloud.sh
- demo_hpc_winter.sh
- ecoli_hpc_winter.sh
- environment.yml
- main.nf
- nextflow.config
- pyproject.toml
- setup.cfg
- src/nanocompare/computeRawReadsCoverage.py
- src/nanocompare/eval_common.py
- src/nanocompare/global_settings.py
- src/nanocompare/read_level_eval.py
- src/nanocompare/site_level_eval.py
- src/nanocompare/tss_eval.py
- src/paper_read_level_performance.sbatch
- src/paper_read_level_performance_submit.sh
- src/paper_site_level_correlation.sbatch
- src/paper_site_level_correlation_submit.sh
- src/paper_tss_data_generation.sbatch
- src/paper_tss_data_generation_submit.sh
- src/paper_unified_format_of_tools.sbatch
- src/plot_figure.py
- utils/FilesSeparator.py
add nanome to PyPI and conda repo
> add to conda package

- conf/executors/lifebit.config
- main.nf
- nextflow.config
Tune cloud computing input params
> Cloud computing params

- conf/examples/test.config
- conf/examples/test_human.config
- conf/executors/lifebit.config
- main.nf
- nextflow.config
> Tutorial refine

- Dockerfile
- README.md
- environment.yml
- main.nf
- modules/BASECALL.nf
- modules/CONSENSUS.nf
- modules/NANOPOLISH.nf
- modules/RESQUIGGLE.nf
- modules/UNTAR.nf
- nextflow.config
- setup.py
- src/nanome/common/global_settings.py
- utils/validate_nanome_container.sh
> update guppy to latest
